export interface LabSpec {
  id: string;
  title: string;
  category: 'control' | 'alignment' | 'rlvr_systems' | 'reasoning';
  icon: string;
  chapterId: string;
  equation: string;
  description: string;
}

export const LAB_CATALOG: Record<string, LabSpec> = {
  cartpole: {
    id: 'cartpole',
    title: 'CartPole 物理動力學與基礎控制模擬器',
    category: 'control',
    icon: '🛒',
    chapterId: 'ch01',
    equation: '\\ddot{\\theta} = \\frac{g \\sin\\theta + \\cos\\theta \\left( \\frac{-F - m_p l \\dot{\\theta}^2 \\sin\\theta}{m_c + m_p} \\right)}{l \\left( \\frac{4}{3} - \\frac{m_p \\cos^2\\theta}{m_c + m_p} \\right)}',
    description: '實時調節小車與擺桿質量比、推力大小與控制頻率，動態觀察二階拉格朗日動力學倒立擺平衡過程。',
  },
  bandit: {
    id: 'bandit',
    title: '多臂老虎機·ε-Greedy 與 UCB1 累積遺憾',
    category: 'control',
    icon: '🎰',
    chapterId: 'ch02',
    equation: 'A_t = \\arg\\max_a \\left[ Q_t(a) + c \\sqrt{\\frac{\\ln t}{N_t(a)}} \\right]',
    description: '模擬 5 臂伯努利老虎機，即時比較純貪婪、ε-Greedy 與 UCB1 信心上限演算法的累積遺憾界限曲線。',
  },
  dqn: {
    id: 'dqn',
    title: 'DQN 經驗回放 (Replay Buffer) 與 TD-Error 震盪',
    category: 'control',
    icon: '🧠',
    chapterId: 'ch03',
    equation: '\\mathcal{L}(\\theta) = \\mathbb{E} \\left[ \\left( r + \\gamma \\max_{a\'} Q(s\', a\'; \\theta^-) - Q(s, a; \\theta) \\right)^2 \\right]',
    description: '動態調整 Replay Buffer 容量與 Target Network 複製週期，觀察 TD 誤差崩塌與 Q 值高估現象。',
  },
  policy_gradient: {
    id: 'policy_gradient',
    title: '策略梯度 REINFORCE 與 Baseline 方差削減',
    category: 'control',
    icon: '📈',
    chapterId: 'ch04',
    equation: '\\nabla_\\theta J(\\theta) = \\mathbb{E} \\left[ \\sum_{t=0}^T \\nabla_\\theta \\log \\pi_\\theta(a_t|s_t) \\left( G_t - b(s_t) \\right) \\right]',
    description: '對比有無 Value Baseline 時梯度估計的方差分佈，體驗方差削減對策略更新穩定度的顯著提升。',
  },
  actor_critic: {
    id: 'actor_critic',
    title: 'Actor-Critic 與 GAE 優勢估計',
    category: 'control',
    icon: '🎭',
    chapterId: 'ch05',
    equation: '\\hat{A}_t^{\\text{GAE}(\\gamma, \\lambda)} = \\sum_{l=0}^{\\infty} (\\gamma \\lambda)^l \\delta_{t+l}^V',
    description: '調節 λ 權重參數在 TD(0) 偏差與蒙地卡羅方差之間平滑過渡，觀察優勢函數的信噪比。',
  },
  continuous: {
    id: 'continuous',
    title: '連續動作空間高斯策略與熵正則化',
    category: 'control',
    icon: '🌊',
    chapterId: 'ch06',
    equation: 'a_t \\sim \\mathcal{N}(\\mu_\\theta(s_t), \\sigma_\\theta^2(s_t)), \\quad \\mathcal{H}(\\pi) = \\frac{1}{2} \\ln(2\\pi e \\sigma^2)',
    description: '實時可視化高斯分佈形變，觀察溫度係數與熵正則項如何防範策略過早坍縮至確定性次優解。',
  },
  offline: {
    id: 'offline',
    title: '離線保守策略 (CQL) 與分佈偏移 (OOD)',
    category: 'control',
    icon: '💾',
    chapterId: 'ch08',
    equation: '\\min_Q \\alpha \\left( \\mathbb{E}_{s \\sim \\mathcal{D}, a \\sim \\mu} [Q(s, a)] - \\mathbb{E}_{(s,a) \\sim \\mathcal{D}} [Q(s, a)] \\right) + \\frac{1}{2} \\mathcal{L}_{\\text{TD}}',
    description: '向離線數據集注入分佈外動作，驗證保守 Q 學習 (CQL) 對致命 Q 值爆炸的壓制效果。',
  },
  ppo: {
    id: 'ppo',
    title: 'PPO 截斷代理目標 (Clipped Objective) 動態',
    category: 'alignment',
    icon: '✂️',
    chapterId: 'ch10',
    equation: 'L^{\\text{CLIP}}(\\theta) = \\hat{\\mathbb{E}}_t \\left[ \\min(r_t(\\theta)\\hat{A}_t, \\text{clip}(r_t(\\theta), 1-\\epsilon, 1+\\epsilon)\\hat{A}_t) \\right]',
    description: '調整比率重要性權重 r_t(θ) 與優勢 A_t，即時可視化悲觀截斷上下界如何約束策略突變。',
  },
  dpo: {
    id: 'dpo',
    title: 'DPO 隱式獎勵邊界 (Direct Preference Optimization)',
    category: 'alignment',
    icon: '🎯',
    chapterId: 'ch11',
    equation: '\\mathcal{L}_{\\text{DPO}} = -\\mathbb{E} \\left[ \\log \\sigma \\left( \\beta \\log \\frac{\\pi_\\theta(y_w|x)}{\\pi_{\\text{ref}}(y_w|x)} - \\beta \\log \\frac{\\pi_\\theta(y_l|x)}{\\pi_{\\text{ref}}(y_l|x)} \\right) \\right]',
    description: '調節溫度係數 β 與偏好勝率，觀察隱式獎勵模型對 Winner 與 Loser 回應的梯度推拉動態。',
  },
  grpo: {
    id: 'grpo',
    title: 'GRPO 群組相對優勢歸一化 (DeepSeek-R1)',
    category: 'alignment',
    icon: '📊',
    chapterId: 'ch12',
    equation: '\\hat{A}_i = \\frac{R_i - \\text{mean}(\\{R_1 \\dots R_G\\})}{\\text{std}(\\{R_1 \\dots R_G\\} + \\epsilon)}',
    description: '調整群組採樣數 G 與獎勵分佈，體驗 DeepSeek-R1 省略 Critic 網絡後的零和群組標準化增益。',
  },
  rlvr_data: {
    id: 'rlvr_data',
    title: 'XML 標籤解析與左側填充 (Left-Padding) 模擬',
    category: 'rlvr_systems',
    icon: '🚀',
    chapterId: 'rlvr01',
    equation: '\\text{Prompt} \\oplus \\text{Reasoning} \\oplus \\text{Answer}, \\quad \\text{Mask}_{\\text{pad}} = 0',
    description: '切換不同品質模型回答樣本，觀察正則提取、標籤覆蓋與 Causal LM 左側填充遮蔽動態。',
  },
  rlvr_rewards: {
    id: 'rlvr_rewards',
    title: '複合獎勵函數加權平衡器 (Multi-Reward)',
    category: 'rlvr_systems',
    icon: '⚖️',
    chapterId: 'rlvr02',
    equation: 'R = w_{\\text{acc}} R_{\\text{acc}} + w_{\\text{fmt}} R_{\\text{fmt}} - \\lambda_{\\text{len}} \\Delta L',
    description: '調整真值準確率、結構格式與長度懲罰權重，觀察對 Goodhart 定律與長度欺騙的防禦效果。',
  },
  rlvr_lora_vram: {
    id: 'rlvr_lora_vram',
    title: '顯卡 VRAM 預算與 LoRA 顯存分配器',
    category: 'rlvr_systems',
    icon: '💾',
    chapterId: 'rlvr04',
    equation: 'W = W_0 + \\frac{\\alpha}{r} B \\times A, \\quad \\text{VRAM} = W_0 + W_{\\text{LoRA}} + \\text{Opt} + \\text{KV} + \\text{Act}',
    description: '選擇基礎模型規格與 LoRA Rank 階數，即時試算 16GB T4 / 24GB 3090 / 80GB A100 下的顯存餘量與 OOM 風險。',
  },
  rlvr_passk: {
    id: 'rlvr_passk',
    title: 'Pass@k 與多數投票 (Majority@k) 組合曲線',
    category: 'reasoning',
    icon: '🎯',
    chapterId: 'rlvr05',
    equation: '\\text{Pass@}k = 1 - \\frac{\\binom{N-c}{k}}{\\binom{N}{k}}, \\quad \\text{Maj@}k = \\arg\\max_a \\text{count}(a)',
    description: '調節單題解率與採樣預算，體驗 Chen et al. 無偏組合估計曲線與多數投票共識率之差異。',
  },
  rlvr_scaling: {
    id: 'rlvr_scaling',
    title: '推理期思考 Token 擴展定律 (Test-Time Scaling)',
    category: 'reasoning',
    icon: '📈',
    chapterId: 'rlvr08',
    equation: '\\text{Acc} \\propto \\alpha \\log(\\text{Tokens}_{\\text{think}}) + \\beta \\log(G), \\quad \\text{FLOPs} \\propto N \\times L',
    description: '調整思考 Token 上限與 Group Size 探索度，探索 DeepSeek-R1 思考長度擴展對複雜數學的對數增益。',
  },
  rlvr_coldstart: {
    id: 'rlvr_coldstart',
    title: 'SFT 冷啟動蒸餾與拒絕採樣 (Rejection Sampling)',
    category: 'rlvr_systems',
    icon: '🧊',
    chapterId: 'rlvr09',
    equation: '\\mathcal{D}_{\\text{SFT}} = \\{ (x, y_i) \\mid r(x, y_i) = 1, \\text{Quality}(y_i) \\ge \\tau \\}',
    description: '調節候選採樣數與思維鏈密度閾值，觀察高質量推理軌跡的保留率與 SFT 暖身樣本分佈。',
  },
  rlvr_distributed: {
    id: 'rlvr_distributed',
    title: '3D-HybridEngine (veRL + vLLM) 分散式架構計算器',
    category: 'rlvr_systems',
    icon: '🌐',
    chapterId: 'rlvr10',
    equation: '\\text{Throughput} \\propto N_{\\text{GPU}} \\times \\text{TPS}_{\\text{vLLM}} \\times (1 - \\text{Comm}_{\\text{TP}})',
    description: '配置叢集 GPU 數量與張量並行 TP，計算 All-Reduce 通訊延遲與 vLLM Zero-Copy PagedAttention 加速比。',
  },
  rlvr_simpo: {
    id: 'rlvr_simpo',
    title: 'SimPO (無參考模型) vs 經典 DPO 邊界對比',
    category: 'alignment',
    icon: '⚡',
    chapterId: 'rlvr11',
    equation: '\\mathcal{L}_{\\text{SimPO}} = -\\log \\sigma \\left( \\frac{\\beta}{|y_w|} \\log \\pi(y_w|x) - \\frac{\\beta}{|y_l|} \\log \\pi(y_l|x) - \\gamma \\right)',
    description: '調整目標邊界 γ 與長度倍率，體驗 SimPO 如何在徹底省去參考模型顯存的同時根治長度偏見。',
  },
  agent_harness: {
    id: 'agent_harness',
    title: 'Agent Harness 四大支柱與執行迴圈模擬器',
    category: 'control',
    icon: '🧩',
    chapterId: 'da01',
    equation: '\\text{Harness} = \\text{Loop}(\\text{Model}, \\text{Tools}) \\oplus \\text{VFS} \\oplus \\text{SubAgents} \\oplus \\text{Memory}',
    description: '動態切換虛擬檔案系統、委派子代理與中介軟體攔截器，觀察 Agent 上下文長度與任務完成率的平衡曲線。',
  },
  agentic: {
    id: 'agentic',
    title: '多代理委派與上下文隔離調度模擬器',
    category: 'control',
    icon: '👥',
    chapterId: 'da06',
    equation: '\\mathcal{C}_{\\text{isolated}} = \\sum_{i} |c_i|, \\quad \\text{Context}_{\\text{main}} \\ll \\mathcal{C}_{\\text{total}}',
    description: '模擬主代理委派專門子代理執行複雜搜尋與分析，體驗上下文隔離技術如何將主視窗 Token 消耗降低 70% 以上。',
  },
  eval_workbench: {
    id: 'eval_workbench',
    title: '五維可觀測性與全生命週期評估工作台',
    category: 'reasoning',
    icon: '🔬',
    chapterId: 'da11',
    equation: '\\text{Score} = \\sum_{k} w_k \\cdot \\text{Rubric}_k, \\quad \\text{Pass@}k = 1 - \\frac{\\binom{N-c}{k}}{\\binom{N}{k}}',
    description: '即時調節工具調用準確率、Rubric 規準權重與軌跡斷言，評估 Agent 在複雜多輪長程任務下的穩定性與成本 Pareto 前緣。',
  },
  agent_vfs: {
    id: 'agent_vfs',
    title: '沙箱 VFS 虛擬檔案系統與權限防護模擬器',
    category: 'control',
    icon: '🛡️',
    chapterId: 'da04',
    equation: '\\text{Access}(p) = \\text{Match}(p, \\text{Rules}) \\in \\{\\text{Allow}, \\text{ReadOnly}, \\text{Deny}\\}',
    description: '測試路徑穿透攻擊與大檔案寫入，即時檢驗 StateBackend 記憶體卸載與 Path-level ACL 阻斷策略。',
  },
  rubric_eval: {
    id: 'rubric_eval',
    title: 'LLM-as-a-Judge 多維度 Rubrics 與 Kappa 一致性檢驗',
    category: 'alignment',
    icon: '⚖️',
    chapterId: 'da12',
    equation: '\\kappa = \\frac{P_o - P_e}{1 - P_e}, \\quad P_o = \\frac{1}{N} \\sum_{i=1}^N \\mathbb{I}(J_{1,i} = J_{2,i})',
    description: '模擬多名 LLM 裁判針對 Agent 輸出進行盲評，調整溫度與評判標準，即時計算 Cohen\'s Kappa 評估者間信度。',
  },
  context_budget: {
    id: 'context_budget',
    title: '動態上下文預算與大文本自動卸載 (Context Offloading)',
    category: 'rlvr_systems',
    icon: '📚',
    chapterId: 'da07',
    equation: '\\text{Budget}_{\\text{remain}} = L_{\\text{max}} - (L_{\\text{prompt}} + L_{\\text{history}} + L_{\\text{tools}})',
    description: '調節工具輸出大小與上下文滿載閾值，動態觀察 20k tokens 自動轉存 VFS 檔案與對話摘要壓縮的觸發動態。',
  },
  pitfalls: {
    id: 'pitfalls',
    title: 'Agent 失效分類 (MAST) 與安全紅隊防禦工作台',
    category: 'reasoning',
    icon: '🚨',
    chapterId: 'da15',
    equation: '\\text{Risk} = P(\\text{Injection}) \\times \\text{BlastRadius}(\\text{Tools})',
    description: '重現間接提示詞注入、委派循環死鎖與工具毒化攻擊，實時觀察雙重防護層與熔斷器的攔截響應。',
  },
};
